version: '3.7'

services:
  ezxssdb:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${dbName}
      - MYSQL_USER=${dbUser}
      - MYSQL_PASSWORD=${dbPassword}
    volumes:
      - "../files/ezxssdb:/var/lib/mysql"
    networks:
      - dokploy-network

  ezxss:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - USE_MAIL_ALERTS=${useMailAlerts}
    volumes:
      - .:/var/www/html
    restart: always
    depends_on:
      - ezxssdb
    environment:
      - INSTALL_CERTIFICATE=${autoInstallCertificate}
      - DOMAIN=${domain}
      - HTTPMODE=${httpmode}
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true
