version: '3.7'

services:
  ezxssdb:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${dbPassword}
      - MYSQL_DATABASE=${dbName}
      - MYSQL_USER=${dbUser}
      - MYSQL_PASSWORD=${dbPassword}
      
  ezxss:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - USE_MAIL_ALERTS=${useMailAlerts}
    volumes:
      - .:/var/www/html
    restart: always
    depends_on:
      - ezxssdb-iks4os0ksogg84cc0s4gsoos
    environment:
      - INSTALL_CERTIFICATE=${autoInstallCertificate}
      - DOMAIN=${domain}
      - HTTPMODE=${httpmode}
